# Railway configuration 

spring.datasource.url=postgresql://postgres:JpUAwCtcwkPMmPYwfXqQsKJsBrganHnw@postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=JpUAwCtcwkPMmPYwfXqQsKJsBrganHnw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080



    - /scan
    - /scan/info
    - /api/qr/image/**

# File Upload Configuration
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB